// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview This file defines a Genkit flow for suggesting objective descriptions,
 * task descriptions, and possible assignees based on a user-provided text prompt.
 *
 * - suggestTasks - The main function to trigger the task suggestion flow.
 * - SuggestTasksInput - The input type for the suggestTasks function.
 * - SuggestTasksOutput - The output type for the suggestTasks function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestTasksInputSchema = z.object({
  objectivePrompt: z
    .string()
    .describe('A text prompt describing the objective for which tasks need to be suggested.'),
});
export type SuggestTasksInput = z.infer<typeof SuggestTasksInputSchema>;

const SuggestTasksOutputSchema = z.object({
  objectiveDescription: z
    .string()
    .describe('A suggested description for the objective based on the prompt.'),
  tasks: z.array(
    z.object({
      taskDescription: z.string().describe('A suggested description for the task.'),
      assignee: z.string().describe('A possible assignee for the task.'),
    })
  ).
  describe('A list of suggested tasks for the objective.'),
});
export type SuggestTasksOutput = z.infer<typeof SuggestTasksOutputSchema>;

export async function suggestTasks(input: SuggestTasksInput): Promise<SuggestTasksOutput> {
  return suggestTasksFlow(input);
}

const suggestTasksPrompt = ai.definePrompt({
  name: 'suggestTasksPrompt',
  input: {schema: SuggestTasksInputSchema},
  output: {schema: SuggestTasksOutputSchema},
  prompt: `You are a task management assistant. Given an objective described in a text prompt, you will suggest a suitable objective description, a list of tasks required to achieve the objective, and a possible assignee for each task.

Objective Prompt: {{{objectivePrompt}}}

Your suggestions should be detailed and actionable.

Output in JSON format.`,
});

const suggestTasksFlow = ai.defineFlow(
  {
    name: 'suggestTasksFlow',
    inputSchema: SuggestTasksInputSchema,
    outputSchema: SuggestTasksOutputSchema,
  },
  async input => {
    const {output} = await suggestTasksPrompt(input);
    return output!;
  }
);
